#!/usr/bin/bash
#----------------------------------------------------------
# This script serves the purpose of adding a random string 
# in a field of a .csv file. Actually, it does not modify 
# the supplied file (for safety), but it creates a new
# suffixed file [filename]_rand[.csv], which is extended
# with respect to the previous by adding a new column
# with a random string at the end of each line (row).
# If the last column is empty, then it is omitted.
# ---------------------------------------------------------
# Written by Vitaly N. Golovach on March 16, 2016
#----------------------------------------------------------
# Set the offset at the start to replace by a specified field
offst=1
offFLD="Random"

# Set the field separator (delimiter) used in the .csv file
fs=","

# Suffixed filename
fullfile=$1
dirF=$(dirname $fullfile)

# Do the separation of the file into path-basename-extension
#filename=$(basename "$1")
filename="${fullfile##*/}"
#extension=".${filename##*.}"
extension=$([[ "$filename" = *.* ]] && echo ".${filename##*.}" || echo '')
filename="${filename%.*}"
# At this point $filename is the basename without extension and path (e.g. file1),
# $extension contains the dot (e.g. .csv), and $dirF is the supplied path of the 
# file which does not contain the last slash (e.g. . and not ./).
#echo $filename
#echo $extension
#echo $dirF
#echo $dirF"/"$filename""$extension

# Set the filemane for the output file, e.g. [filename]_rand[.csv] 
file2=$dirF"/"$filename"_rand"$extension

# See if file already exists
if [ -f $file2 ]; then
echo "The file "$file2" already exists."
  echo -n "Would you like to overwrite it [yes/no]: "
  read varYN
  if [ "$varYN" == "yes" ]; then
    rm $file2
  else
    echo "Exiting without making any changes."
    exit 1
  fi
fi
touch $file2


# Check to see if the last filed is consistently fully empty
flg01=$(gawk -v vfs="$fs" 'BEGIN{FS=vfs; flg=0}{ \
  fld=$NF; gsub(/^[ \t]+|[ \t]+$/, "", fld);\
  if(fld!=""){flg=1} \
  }END{print flg}' $1)

echo "$flg01"

# Decide whether to set or not to set a delimiter 
# to the left of the new field
if [ "$flg01" -eq "1" ]; then
 fsD=$fs
else
 fsD=""
fi

#get the number of lines in the file
nl=$(gawk 'BEGIN{}{}END{print NR}' $1)
# Loop through the lines
cnt=1
while [ $cnt -le $nl ]; do
if [ $cnt -le $offst ]; then
  #get the full record of the current line of file1.csv
  recfile1=$(gawk -v vnl=$cnt -v vfs="$fs" \
  'BEGIN{FS=vfs}{if(NR==vnl){rec=$0}}END{print rec}' $1)
  #extend the record
  rec=$recfile1""$fsD""$offFLD 
  #add it to second file
  echo $rec>>$file2 
else
  #get the full record of the current line of file1.csv
  recfile1=$(gawk -v vnl=$cnt -v vfs="$fs" \
  'BEGIN{FS=vfs}{if(NR==vnl){rec=$0}}END{print rec}' $1)
  #get a random string
  rndstr=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 64 | head -n 1)
  #extend the record
  rec=$recfile1""$fsD""$rndstr
  #add it to second file
  echo $rec>>$file2 
fi
 let cnt=cnt+1
done
